
services:
    web:
        build: .
        command: python3 /code/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - eCommerce/.env
    db:
        image: mysql:8.0.40
        restart: always
        command: --default-authentication-plugin=mysql_native_password --mysqlx=0
        environment:
            MYSQL_DATABASE: eCommerce
            MYSQL_USER: trung
            MYSQL_PASSWORD: Miasanmia22@
            MYSQL_ROOT_PASSWORD: Miasanmia1@
        volumes:
            - ".dbdata:/var/lib/mysql"
        ports:
            - '3305:3306'
        env_file:
            - eCommerce/.env
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
